[project]
name = "agentic-bootcamp-starter"
version = "0.1.0"
description = "Starter repo for a 4-week Agentic AI bootcamp"
requires-python = ">=3.9"
dependencies = []

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-q"
